USEMODULE += boards_common_atmega

ifneq (,$(filter netdev_default,$(USEMODULE)))
  USEMODULE += cc1101
endif

ifneq (,$(filter xtimer,$(USEMODULE)))
  ifeq (,$(filter ztimer_xtimer_compat,$(USEMODULE)))
    # Board is not compatible with xtimer due to 12 MHz core clock
    USEMODULE += xtimer_on_ztimer
  endif
endif
