USEMODULE += boards_common_atmega

ifneq (,$(filter netdev_default,$(USEMODULE)))
  USEMODULE += cc1101
endif

ifneq (,$(filter mtd,$(USEMODULE)))
  USEMODULE += mtd_sdcard
endif

# default to using fatfs on SD card
ifneq (,$(filter vfs_default,$(USEMODULE)))
  USEMODULE += fatfs_vfs
  USEMODULE += mtd
endif
