USEMODULE += boards_common_blxxxpill

ifneq (,$(filter saul_default,$(USEMODULE)))
  USEMODULE += servo
endif

ifneq (,$(filter netdev_default,$(USEMODULE)))
  USEMODULE += nrf24l01p_ng
endif

include $(RIOTBOARD)/common/blxxxpill/Makefile.dep
# stdio over USB would be nice, but I fail to get it working
include $(RIOTBOARD)/common/makefiles/stdio_cdc_acm.dep.mk
